# Generated by Django 4.1.2 on 2022-10-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoardGamesAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_review',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
