# Generated by Django 4.1.2 on 2022-10-24 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BoardGamesAPI', '0002_alter_t_review_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_user_activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Activity_Type', models.CharField(max_length=30, unique=True)),
                ('Activity_Timestamp', models.DateTimeField()),
                ('User_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BoardGamesAPI.t_user')),
            ],
        ),
    ]
