#Deriving the latest base image
FROM python:3

# Any working directory can be chosen as per choice like '/' or '/home' etc
# i have chosen /usr/app/src
RUN mkdir /Recomendation_Service
WORKDIR /Recomendation_Service
ADD . /Recomendation_Service/

RUN pip install -r requirements.txt

CMD ["python","./SendRequest.py"]
