FROM python:3.9

RUN apt update && \
    apt install --no-install-recommends -y build-essential gcc && \
    apt clean && rm -rf /var/lib/apt/lists/*

#ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /BoardGame_Backend
ADD . /BoardGame_Backend/

RUN pip3 --no-cache-dir install -r requirements.txt

