FROM python:3
#ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

#RUN mkdir /BoardGame_Backen
WORKDIR /BoardGame_Backend
ADD . /BoardGame_Backend/

RUN pip install apscheduler
#RUN pip install tensorflow
RUN pip install -r requirements.txt
