FROM python:3
#ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN mkdir /BoardGame_Service
WORKDIR /BoardGame_Service
ADD . /BoardGame_Service/

RUN pip install apscheduler
RUN pip install -r requirements.txt
