
FROM node:16.16.0-alpine

#RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
#RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
#RUN apt-get update && apt-get install -yq google-chrome-stable

#RUN mkdir /install
#ADD ./package.json /install

#WORKDIR /install
USER node
WORKDIR /app

COPY package*.json ./

USER root
#RUN apt-get update && apt-get install -y vim
#RUN mkdir /home/node/.npm-global
#ENV PATH=/home/node/.npm-global/bin:$PATH
#ENV NPM_CONFIG_PREFIX=/home/node/.npm-global

RUN npm install -g npm@6
RUN npm install -g @angular/cli@14.1.3
RUN npm install
RUN npm build

ENV NODE_PATH /install/node_modules

COPY ./ /app

EXPOSE 4200

CMD ["npm", "start", "--", "--host", "0.0.0.0", "--poll", "500"]
#COPY ./src .

#COPY . .
#WORKDIR /app
#COPY . /app/
