
FROM node:16.16.0-alpine

USER node
WORKDIR /BoardGame_Frontend
COPY package*.json ./

USER root

RUN npm install -g npm@6
RUN npm install -g @angular/cli@14.1.3
RUN npm install
RUN npm build

ENV NODE_PATH /install/node_modules

COPY ./ /BoardGame_Frontend

EXPOSE 4200

