
FROM node:16.16.0-alpine

#RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
#RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
#RUN apt-get update && apt-get install -yq google-chrome-stable

WORKDIR /app
#RUN apt-get update && apt-get install -y vim

#USER node

#RUN mkdir /home/node/.npm-global
#ENV PATH=/home/node/.npm-global/bin:$PATH
#ENV NPM_CONFIG_PREFIX=/home/node/.npm-global

EXPOSE 4200

ENV PATH /app/node_modules/.bin:$PATH

COPY package.json /app/package.json

RUN npm install -g npm@6
RUN npm install -g @angular/cli@14.1.3
RUN ng update @angular/cli @angular/core

RUN npm install
COPY . /app


#CMD ng serve --host 0.0.0.0